// packages/solid/src/types/polymorphic.ts
import type { JSX } from "solid-js";

import type { SupportedComponentProps, SupportedElementType } from "./solid";

type ResolveRefProps<P extends {}> = Omit<P, "ref"> & {
  ref?: P extends {
    ref?: infer Ref;
  }
    ? Ref
    : unknown;
};

export type PolymorphicComponentProps<ET extends SupportedElementType, Props = {}> = (Props & {
  as?: ET;
} & {
  children?: JSX.Element;
}) &
  Omit<ResolveRefProps<SupportedComponentProps<ET>>, "as" | keyof Props>;

// packages/qwik/src/types/polymorphic.ts
import type { JSXChildren } from "@builder.io/qwik";

import type { SupportedComponentProps, SupportedElementType } from "./qwik";

type ResolveRefProps<P extends {}> = Omit<P, "ref"> & {
	ref?: P extends {
		ref?: infer Ref;
	}
		? Ref
		: unknown;
};

export type PolymorphicComponentProps<ET extends SupportedElementType, Props = {}> = (Props & {
	as?: ET;
} & {
	children?: JSXChildren;
}) &
	Omit<ResolveRefProps<SupportedComponentProps<ET>>, "as" | keyof Props>;
